update app names

diff --git a/git-ops/bin/vezuvio b/git-ops/bin/vezuvio
--- a/git-ops/bin/vezuvio
+++ b/git-ops/bin/vezuvio
@@ -6,7 +6,7 @@ set -u
 # shellcheck disable=SC2292
 if [ -z "${BASH_VERSION:-}" ]
 then
-  echo "Error: Bash is required to run tray." >&2
+  echo "Error: Bash is required to run vezuvio." >&2
   exit 1
 fi
 
@@ -15,24 +15,24 @@ set +o posix # as we are using bash now
 # Fail fast with concise messages when PWD has issues
 if [[ -z "${PWD-}" ]]
 then
-  echo "Error: \$PWD must be set to run tray." >&2
+  echo "Error: \$PWD must be set to run vezuvio." >&2
   exit 1
 fi
 if ! [[ -d "${PWD}" ]]
 then
-  echo "Error: The current working directory must exist to run tray." >&2
+  echo "Error: The current working directory must exist to run vezuvio." >&2
   exit 1
 fi
 if ! [[ -r "${PWD}" ]]
 then
-  echo "Error: The current working directory must be readable to ${USER} to run tray." >&2
+  echo "Error: The current working directory must be readable to ${USER} to run vezuvio." >&2
   exit 1
 fi
 
 # Fail fast with concise message when HOME is unset
 if [[ -z "${HOME:-}" ]]
 then
-  echo "Error: \$HOME must be set to run tray." >&2
+  echo "Error: \$HOME must be set to run vezuvio." >&2
   exit 1
 fi
 
@@ -43,32 +43,32 @@ fi
 # SCRIPTPATH=$(dirname "$SCRIPT")
 
 # shellcheck disable=SC2116
-TRAY_HOME_DEFAULT=$(echo ~/.tray)
-TRAY_HOME=$TRAY_HOME_DEFAULT
+VEZUVIO_HOME_DEFAULT=$(echo ~/.vezuvio)
+VEZUVIO_HOME=$VEZUVIO_HOME_DEFAULT
 
 currentDir=$(pwd)
 # Check the number of arguments
 if [ "$#" -lt 1 ]; then
     echo "Missing arguments"
-    echo "Usage: tray <arg1> <arg2>"
+    echo "Usage: vezuvio <arg1> <arg2>"
     exit 1
 fi
 
 if [ "$#" -eq 1 ]; then
-    cd "${TRAY_HOME}"/repository || exit
+    cd "${VEZUVIO_HOME}"/repository || exit
     ./gradlew clean -PisProduction=1 -Dorg.gradle.logging.level=quiet --console=plain app:run --args="$1"
     cd "${currentDir}"  || exit
 elif [ "$#" -eq 2 ]; then
-    cd "${TRAY_HOME}"/repository || exit
+    cd "${VEZUVIO_HOME}"/repository || exit
     ./gradlew clean -PisProduction=1 -Dorg.gradle.logging.level=quiet --console=plain app:run --args="$1 $2"
     cd "${currentDir}"  || exit
 elif [ "$#" -eq 3 ]; then
-    cd "${TRAY_HOME}"/repository || exit
+    cd "${VEZUVIO_HOME}"/repository || exit
     ./gradlew clean -PisProduction=1 -Dorg.gradle.logging.level=quiet --console=plain app:run --args="$1 $2 $3"
     cd "${currentDir}" || exit
 else
     echo "Too many arguments"
-    echo "Usage: tray <arg1> <arg2>"
+    echo "Usage: vezuvio <arg1> <arg2>"
     exit 1
 fi
 
